[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.package-data]
"*" = ["py.typed", "*.pyi"]

[project]
name = "lionweb"
version = "0.4.1"
description = "A Python package for working with LionWeb"
readme = "README.md"
authors = [{ name = "Federico Tomassetti", email = "federico@strumenta.com" }]
license = { file = "LICENSE.txt" }
requires-python = ">=3.11"
dependencies = [
    "requests",
    "pydantic",
    "typing_extensions>=4.8",
    "protobuf",
    "click",
    "astor"
]

[project.scripts]
lionweb-gen = "lionweb.generation.generator:main"

[project.optional-dependencies]
dev = [
    "coverage",
    "diff-cover",
    "testcontainers>=4.0",
    "types-requests",
]

[tool.ruff]
line-length = 100

[tool.ruff.lint]
select = ["E", "F", "W", "I", "UP"]
ignore = ["E501"]

[tool.ruff.lint.per-file-ignores]
"tests/**" = ["F401"]
"src/lionweb/serialization/proto/**" = ["E", "F", "W", "I", "UP"]

[tool.mypy]
python_version = "3.13"
mypy_path = "src"
namespace_packages = true