name: Check Python

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.9.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.9.6
    - name: Install deps
      run: pip install -r Requirements.txt
    - name: Test
      run: PYTHONPATH=src python -m unittest discover tests
    - name: Linting
      run: ruff check src/ tests/
    - name: Checking types
      run: mypy src/